"""Adiciona data_criacao em Comunicados

Revision ID: 17facb4e5fc0
Revises: ee697a5f8046
Create Date: 2025-02-12 23:49:12.740735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17facb4e5fc0'
down_revision: Union[str, None] = 'ee697a5f8046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
