"""Adiciona endereco ao condominio

Revision ID: 2844966c755e
Revises: ad4fa36b9bc8
Create Date: 2025-02-11 21:09:21.606035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2844966c755e'
down_revision: Union[str, None] = 'ad4fa36b9bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comunicados_id', table_name='comunicados')
    op.drop_index('ix_comunicados_titulo', table_name='comunicados')
    op.drop_table('comunicados')
    op.drop_index('ix_atas_id', table_name='atas')
    op.drop_index('ix_atas_titulo', table_name='atas')
    op.drop_table('atas')
    op.drop_index('ix_condominios_id', table_name='condominios')
    op.drop_index('ix_condominios_nome', table_name='condominios')
    op.drop_table('condominios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('condominios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='condominios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_condominios_nome', 'condominios', ['nome'], unique=True)
    op.create_index('ix_condominios_id', 'condominios', ['id'], unique=False)
    op.create_table('atas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], name='atas_condominio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='atas_pkey')
    )
    op.create_index('ix_atas_titulo', 'atas', ['titulo'], unique=False)
    op.create_index('ix_atas_id', 'atas', ['id'], unique=False)
    op.create_table('comunicados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_publicacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], name='comunicados_condominio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comunicados_pkey')
    )
    op.create_index('ix_comunicados_titulo', 'comunicados', ['titulo'], unique=False)
    op.create_index('ix_comunicados_id', 'comunicados', ['id'], unique=False)
    # ### end Alembic commands ###
