"""Add endereco field to Condominio

Revision ID: ad4fa36b9bc8
Revises: 8ee6ade9262b
Create Date: 2025-02-11 20:33:47.975960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4fa36b9bc8'
down_revision: Union[str, None] = '8ee6ade9262b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
