"""Adiciona data_criacao em Comunicados

Revision ID: ee697a5f8046
Revises: 2844966c755e
Create Date: 2025-02-12 23:40:30.786238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee697a5f8046'
down_revision: Union[str, None] = '2844966c755e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_condominios_id', table_name='condominios')
    op.drop_index('ix_condominios_nome', table_name='condominios')
    op.execute('DROP TABLE IF EXISTS condominios CASCADE')
    op.drop_index('ix_atas_id', table_name='atas')
    op.drop_index('ix_atas_titulo', table_name='atas')
    op.drop_table('atas')
    op.drop_index('ix_comunicados_id', table_name='comunicados')
    op.drop_index('ix_comunicados_titulo', table_name='comunicados')
    op.drop_table('comunicados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_publicacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], name='comunicados_condominio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comunicados_pkey')
    )
    op.create_index('ix_comunicados_titulo', 'comunicados', ['titulo'], unique=False)
    op.create_index('ix_comunicados_id', 'comunicados', ['id'], unique=False)
    op.create_table('atas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], name='atas_condominio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='atas_pkey')
    )
    op.create_index('ix_atas_titulo', 'atas', ['titulo'], unique=False)
    op.create_index('ix_atas_id', 'atas', ['id'], unique=False)
    op.create_table('condominios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='condominios_pkey')
    )
    op.create_index('ix_condominios_nome', 'condominios', ['nome'], unique=True)
    op.create_index('ix_condominios_id', 'condominios', ['id'], unique=False)
    # ### end Alembic commands ###
